"""add processed_reason to triage_classifications

Revision ID: 4b639b6a5062
Revises: drop_response_tracking
Create Date: 2026-04-24 07:42:25.211131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b639b6a5062'
down_revision: Union[str, None] = 'drop_response_tracking'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_source_exclusions_channel_id'), table_name='channel_source_exclusions')
    op.drop_constraint(op.f('uq_channel_source_exclusion_entity'), 'channel_source_exclusions', type_='unique')
    op.alter_column('checkpoints', 'checkpoint',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_focus_mode_state_is_active'), table_name='focus_mode_state')
    op.drop_index(op.f('ix_focus_mode_state_user_id'), table_name='focus_mode_state')
    op.drop_index(op.f('ix_focus_vip_list_user_id'), table_name='focus_vip_list')
    op.drop_constraint(op.f('uq_focus_vip_list_user_slack'), 'focus_vip_list', type_='unique')
    op.drop_index(op.f('ix_memories_type'), table_name='memories')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.alter_column('messages', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_monitored_channels_slack_channel_id'), table_name='monitored_channels')
    op.drop_index(op.f('ix_monitored_channels_user_id'), table_name='monitored_channels')
    op.drop_constraint(op.f('uq_monitored_channels_user_channel'), 'monitored_channels', type_='unique')
    op.drop_index(op.f('ix_notes_tags'), table_name='notes', postgresql_using='gin')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_user_id_is_archived'), table_name='notes')
    op.drop_constraint(op.f('uq_sender_behavior_user_sender'), 'sender_behavior_models', type_='unique')
    op.create_table_comment(
        'sender_behavior_models',
        'UNIQUE(user_id, sender_slack_id) enforced via migration index',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_sessions_source'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id_is_starred'), table_name='sessions')
    op.drop_index(op.f('ix_todos_recurrence_parent_id'), table_name='todos')
    op.drop_index(op.f('ix_todos_user_id'), table_name='todos')
    op.drop_index(op.f('ix_todos_user_id_due_at'), table_name='todos')
    op.drop_index(op.f('ix_todos_user_id_status'), table_name='todos')
    op.add_column('triage_classifications', sa.Column('processed_reason', sa.String(length=30), nullable=True))
    op.alter_column('triage_classifications', 'last_alerted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_triage_last_alerted_sender'), table_name='triage_classifications')
    op.drop_index(op.f('idx_triage_last_alerted_thread'), table_name='triage_classifications', postgresql_where='(thread_ts IS NOT NULL)')
    op.drop_index(op.f('idx_triage_queued_digest'), table_name='triage_classifications', postgresql_where='(queued_for_digest = true)')
    op.drop_index(op.f('ix_triage_classifications_created'), table_name='triage_classifications')
    op.drop_index(op.f('ix_triage_classifications_digest_type'), table_name='triage_classifications', postgresql_where='(digest_type IS NOT NULL)')
    op.drop_index(op.f('ix_triage_classifications_session'), table_name='triage_classifications')
    op.drop_index(op.f('ix_triage_classifications_urgency'), table_name='triage_classifications')
    op.drop_index(op.f('ix_triage_classifications_user_id'), table_name='triage_classifications')
    op.drop_index(op.f('ix_triage_classifications_user_reviewed'), table_name='triage_classifications')
    op.drop_index(op.f('ix_triage_feedback_classification_id'), table_name='triage_feedback')
    op.drop_index(op.f('ix_user_oauth_tokens_user_id'), table_name='user_oauth_tokens')
    op.drop_index(op.f('ix_webhook_subscriptions_user_id'), table_name='webhook_subscriptions')
    op.drop_index(op.f('ix_youtube_playlists_user_id'), table_name='youtube_playlists')
    op.drop_index(op.f('ix_youtube_playlists_user_id_is_active'), table_name='youtube_playlists')
    op.drop_index(op.f('ix_youtube_videos_playlist_id'), table_name='youtube_videos')
    op.drop_index(op.f('ix_youtube_videos_playlist_status_sort'), table_name='youtube_videos')
    op.drop_index(op.f('ix_youtube_videos_user_id'), table_name='youtube_videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_youtube_videos_user_id'), 'youtube_videos', ['user_id'], unique=False)
    op.create_index(op.f('ix_youtube_videos_playlist_status_sort'), 'youtube_videos', ['playlist_id', 'status', 'sort_order'], unique=False)
    op.create_index(op.f('ix_youtube_videos_playlist_id'), 'youtube_videos', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_youtube_playlists_user_id_is_active'), 'youtube_playlists', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_youtube_playlists_user_id'), 'youtube_playlists', ['user_id'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_user_id'), 'webhook_subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_oauth_tokens_user_id'), 'user_oauth_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_triage_feedback_classification_id'), 'triage_feedback', ['classification_id'], unique=True)
    op.create_index(op.f('ix_triage_classifications_user_reviewed'), 'triage_classifications', ['user_id', 'reviewed_at'], unique=False)
    op.create_index(op.f('ix_triage_classifications_user_id'), 'triage_classifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_triage_classifications_urgency'), 'triage_classifications', ['user_id', 'priority_level'], unique=False)
    op.create_index(op.f('ix_triage_classifications_session'), 'triage_classifications', ['user_id', 'focus_session_id'], unique=False)
    op.create_index(op.f('ix_triage_classifications_digest_type'), 'triage_classifications', ['digest_type'], unique=False, postgresql_where='(digest_type IS NOT NULL)')
    op.create_index(op.f('ix_triage_classifications_created'), 'triage_classifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_triage_queued_digest'), 'triage_classifications', ['user_id', 'priority_level', 'queued_for_digest'], unique=False, postgresql_where='(queued_for_digest = true)')
    op.create_index(op.f('idx_triage_last_alerted_thread'), 'triage_classifications', ['user_id', 'thread_ts', 'last_alerted_at'], unique=False, postgresql_where='(thread_ts IS NOT NULL)')
    op.create_index(op.f('idx_triage_last_alerted_sender'), 'triage_classifications', ['user_id', 'sender_slack_id', 'last_alerted_at'], unique=False)
    op.alter_column('triage_classifications', 'last_alerted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('triage_classifications', 'processed_reason')
    op.create_index(op.f('ix_todos_user_id_status'), 'todos', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_todos_user_id_due_at'), 'todos', ['user_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_todos_user_id'), 'todos', ['user_id'], unique=False)
    op.create_index(op.f('ix_todos_recurrence_parent_id'), 'todos', ['recurrence_parent_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id_is_starred'), 'sessions', ['user_id', 'is_starred'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_source'), 'sessions', ['source'], unique=False)
    op.drop_table_comment(
        'sender_behavior_models',
        existing_comment='UNIQUE(user_id, sender_slack_id) enforced via migration index',
        schema=None
    )
    op.create_unique_constraint(op.f('uq_sender_behavior_user_sender'), 'sender_behavior_models', ['user_id', 'sender_slack_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_notes_user_id_is_archived'), 'notes', ['user_id', 'is_archived'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_index(op.f('ix_notes_tags'), 'notes', ['tags'], unique=False, postgresql_using='gin')
    op.create_unique_constraint(op.f('uq_monitored_channels_user_channel'), 'monitored_channels', ['user_id', 'slack_channel_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_monitored_channels_user_id'), 'monitored_channels', ['user_id'], unique=False)
    op.create_index(op.f('ix_monitored_channels_slack_channel_id'), 'monitored_channels', ['slack_channel_id'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.alter_column('messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_index(op.f('ix_memories_type'), 'memories', ['type'], unique=False)
    op.create_unique_constraint(op.f('uq_focus_vip_list_user_slack'), 'focus_vip_list', ['user_id', 'slack_user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_focus_vip_list_user_id'), 'focus_vip_list', ['user_id'], unique=False)
    op.create_index(op.f('ix_focus_mode_state_user_id'), 'focus_mode_state', ['user_id'], unique=False)
    op.create_index(op.f('ix_focus_mode_state_is_active'), 'focus_mode_state', ['is_active'], unique=False)
    op.alter_column('checkpoints', 'checkpoint',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_channel_source_exclusion_entity'), 'channel_source_exclusions', ['monitored_channel_id', 'slack_entity_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_channel_source_exclusions_channel_id'), 'channel_source_exclusions', ['monitored_channel_id'], unique=False)
    # ### end Alembic commands ###
