"""add summary_behavior to monitored_channel

Revision ID: de9e5c6ca05a
Revises: 4b639b6a5062
Create Date: 2026-04-27 05:15:16.460323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9e5c6ca05a'
down_revision: Union[str, None] = '4b639b6a5062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_channels', sa.Column('summary_behavior', sa.String(length=20), server_default='default', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitored_channels', 'summary_behavior')
    # ### end Alembic commands ###
